cache: 
  - /tmp/github
image: dockerfile/nginx
script:
  - echo hello world
  - cat /etc/issue
  - sudo ifconfig | grep eth0
  - ls
  - docker ps
  - cd /var/cache/drone/src/github.com/needf/myfirst&&ls
