#!/bin/sh

salutation="Hellow"
echo $salutation 
echo "The program $0 is now running"
echo "The second parameter was $2"

echo "please enter a new greeting"
read salutation

echo $salutation
echo "The script is now complete"
exit 0
